repos:
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.64.dss
    hooks:
      - id: detect-secrets # pragma: whitelist secret
        args: [--baseline, .secrets.baseline, --use-all-plugins]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=100"]
